### ISSUE TITLE
Example is not working

### ISSUE THREAD

**Issue by giubaru** [taskiq-python/taskiq-nats#14]
Hello!
I wanted to try using taskiq-nats in my project, but while testing the example shown in the README, it is not working.
I was trying different configurations and Nats servers but the task execution is not working.

Taskiq connects to the nats server but when I want to do the task.kiq() it doesn't execute, I don't know if I'm missing something or if this integration is still too green to start using it in a project.

Some details:

I am running Nats in docker as follows:

 `docker run --name nats --rm -rm -p 4222:4222 nats`

and my script is:

```python
import asyncio
from taskiq_nats import NatsBroker

broker = NatsBroker(
    [
        "nats://localhost:4222"
    ],
    queue="test_queue"
)


@broker.task
async def my_lovely_task():
    print("I love taskiq")


async def main():
    await broker.startup()
    print('Broker running...')

    await my_lovely_task.kiq()
    print('Kicked task..')

    await broker.shutdown()
    print('Done')

if __name__ == "__main__":
    print('Running task...')
    asyncio.run(main())


```

the output:

```
python -m src.example_task

Running task...
Broker running...
Kicked task..
Done
```

Thank you very much for all the work done and I will try to contribute as much as I can.

**Comment by chandr-andr** [comment]
Hello!
You need to run worker as a separate process.
You can look at the docs - https://taskiq-python.github.io/guide/getting-started.html#distributed-run.
